INSERT INTO constellation (constellation_name, constellation_code) VALUES
('Andromeda', 'and'),
('Leo', 'leo'),
('Antlia', 'ant'),
('Leo Minor', 'lmi'),
('Aps', 'aps'),
('Apus', 'aql'),
('Lepus', 'lep'),
('Aquarius', 'aqr'),
('Libra', 'lib'),
('Aquila', 'aql'),
('Lupus', 'lup'),
('Ara', 'ara'),
('Lynx', 'lyn'),
('Aries', 'ari'),
('Lyra', 'lyr'),
('Auriga', 'aur'),
('Mensa', 'men'),
('Boötes', 'boo'),
('Microscopium', 'mic'),
('Caelum', 'cae'),
('Monoceros', 'mon'),
('Camelopardalis', 'cam'),
('Musca', 'mus'),
('Cancer', 'cnc'),
('Norma', 'nor'),
('Canes Venatici', 'cvn'),
('Octans', 'oct'),
('Canis Major', 'cma'),
('Ophiuchus', 'oph'),
('Canis Minor', 'cmi'),
('Orion', 'ori'),
('Capricornus', 'cap'),
('Pavo', 'pav'),
('Carina', 'car'),
('Pegasus', 'peg'),
('Cassiopeia', 'cas'),
('Perseus', 'per'),
('Centaurus', 'cen'),
('Phoenix', 'phe'),
('Cepheus', 'cep'),
('Pictor', 'pic'),
('Cetus', 'cet'),
('Pisces', 'psc'),
('Chamaeleon', 'cha'),
('Piscis Austrinus', 'psa'),
('Circinus', 'cir'),
('Puppis', 'pup'),
('Columba', 'col'),
('Pyxis', 'pyx'),
('Coma Berenices', 'com'),
('Reticulum', 'ret'),
('Corona Australis', 'cra'),
('Sagitta', 'sge'),
('Corona Borealis', 'crb'),
('Sagittarius', 'sgr'),
('Corvus', 'crv'),
('Scorpius', 'sco'),
('Crater', 'crt'),
('Sculptor', 'scl'),
('Crux', 'cru'),
('Scutum', 'sct'),
('Cygnus', 'cyg'),
('Serpens', 'ser'),
('Delphinus', 'del'),
('Dorado', 'dor'),
('Sextans', 'sex'),
('Draco', 'dra'),
('Taurus', 'tau'),
('Equuleus', 'equ'),
('Telescopium', 'tel'),
('Eridanus', 'eri'),
('Triangulum', 'tri'),
('Fornax', 'for'),
('Triangulum Australe', 'tra'),
('Gemini', 'gem'),
('Tucana', 'tuc'),
('Grus', 'gru'),
('Ursa Major', 'uma'),
('Hercules', 'her'),
('Ursa Minor', 'umi'),
('Horologium', 'hor'),
('Vela', 'vel'),
('Hydra', 'hya'),
('Virgo', 'vir'),
('Hydrus', 'hyi'),
('Volans', 'vol'),
('Indus', 'ind'),
('Vulpecula', 'vul'),
('Lacerta', 'lac');
