name: Pylint Workflow  

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  lint:
      runs-on: ubuntu-latest  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 
          with:
              python-version: '3.11'
  
        - name: Set up Python
          uses: actions/setup-python@v4  
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip 
            pip install pylint  
        - name: Run pylint
          run: |
            if ls **/*.py 1> /dev/null 2>&1; then
              flake8 .
            else
              echo "No Python files found, skipping linting."
            fi